# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React App Deploy to Surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12
          
    - uses: borales/actions-yarn@v2.0.0
      with:
          cmd: install # will run `yarn install` command
          
    - name: Build React App
      run: yarn build
            
      -name: Install Surge
        run: npm install -g surge
             
       -name: Deploy to Surge
        run: surge ./build project003-umair.surge.sh --token ${{ secrets.SURGE_TOKEN }}
          
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
